name: 🤖 Android Build and Distribution

on:
  workflow_call:
    secrets:
      KEYSTORE_PASSWORD: { required: true }
      KEY_PASSWORD: { required: true }
      KEY_ALIAS: { required: true }
      ANDROID_APP_ID: { required: true }
      FIREBASE_TOKEN: { required: true }

jobs:
  build_android:
    runs-on: macos-latest

    env:
      ANDROID_APP_PATH: composeApp
      TESTER_GROUP: "new-release-updates"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Download Keystore (from parent job)
      - name: Download Keystore Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-signing-keystore
          path: composeApp/

      - name: Setup Android SDK & Build Tools
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0

      # 2. FIX: Install Firebase Tools within this job
      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      # 3. Build Android APK (Pass secrets via -P properties)
      - name: Build Android APK
        run: |
          ./gradlew :composeApp:assembleRelease \
            -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
            -PKEY_ALIAS=${{ secrets.KEY_ALIAS }} \
            -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }}

      # 4. Find and Upload APK
      - name: Find and Upload APK
        id: find_apk
        run: |
          ANDROID_OUTPUT_DIR="$ANDROID_APP_PATH/build/outputs/apk/release"
          APK_FILE_PATH=$(find "$ANDROID_OUTPUT_DIR" -name "*.apk" -print -quit)
          
          # The 'firebase' command is now available
          firebase appdistribution:distribute "$APK_FILE_PATH" \
            --app "${{ secrets.ANDROID_APP_ID }}" \
            --groups "$TESTER_GROUP" \
            --release-notes "Android build from GitHub Actions - Commit ${{ github.sha }}" \
            --token "${{ secrets.FIREBASE_TOKEN }}"