name: Firebase Distribution (KMP)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  distribute:
    runs-on: macos-latest

    env:
      ANDROID_APP_PATH: composeApp
      IOS_APP_PATH: iosApp
      ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
      IOS_APP_ID: ${{ secrets.IOS_APP_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      TESTER_GROUP: "new-release-updates"

    steps:
      # ---------- 1. Checkout ----------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- 2. Setup JDK ----------
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # ---------- 3. Increment Android version ----------
      - name: Increment Android versionCode
        run: |
          FILE="$ANDROID_APP_PATH/build.gradle.kts"
          VERSION_CODE=$(date +%s)
          sed -i "" "s/versionCode [0-9]\+/versionCode $VERSION_CODE/" $FILE
          VERSION_NAME="1.0.$VERSION_CODE"
          sed -i "" "s/versionName \".*\"/versionName \"$VERSION_NAME\"/" $FILE
          echo "Android versionCode=$VERSION_CODE, versionName=$VERSION_NAME"

      # ---------- 4. Build Android APK ----------
      - name: Build Android APK
        run: ./gradlew :composeApp:assembleRelease

      # ---------- 5. Upload Android to Firebase ----------
      - name: Upload Android to Firebase
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute $ANDROID_APP_PATH/build/outputs/apk/release/composeApp-release.apk \
            --app "$ANDROID_APP_ID" \
            --groups "$TESTER_GROUP" \
            --release-notes "Android build from GitHub Actions - Commit ${{ github.sha }}" \
            --token "$FIREBASE_TOKEN"

      # ---------- 6. Setup Xcode ----------
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      # ---------- 7. Build KMP iOS Framework ----------
      - name: Build KMP iOS Framework
        run: ./gradlew :shared:packForXcode

      # ---------- 8. Increment iOS build number ----------
      - name: Increment iOS build number
        run: |
          BUILD_NUMBER=$(date +%s)
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" $IOS_APP_PATH/iosApp/Info.plist
          echo "iOS build number set to $BUILD_NUMBER"

      # ---------- 9. Build iOS IPA ----------
      - name: Build iOS IPA
        run: |
          cd $IOS_APP_PATH
          xcodebuild \
            -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/iosApp.xcarchive archive
          xcodebuild \
            -exportArchive \
            -archivePath build/iosApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build

      # ---------- 10. Upload iOS to Firebase ----------
      - name: Upload iOS to Firebase
        run: |
          npm install -g firebase-tools
          firebase appdistribution:distribute $IOS_APP_PATH/build/iosApp.ipa \
            --app "$IOS_APP_ID" \
            --groups "$TESTER_GROUP" \
            --release-notes "iOS build from GitHub Actions - Commit ${{ github.sha }}" \
            --token "$FIREBASE_TOKEN"
