name: 🍏 iOS Build and Distribution (KMP ComposeApp)

on:
  workflow_call:
    secrets:
      IOS_APP_ID: { required: true }
      FIREBASE_TOKEN: { required: true }
      # Android secrets required for Gradle config phase (ONLY if your Gradle files require them to merely parse)
      KEYSTORE_PASSWORD: { required: true }
      KEY_ALIAS: { required: true }
      KEY_PASSWORD: { required: true }

jobs:
  build_ios:
    runs-on: macos-latest

    env:
      IOS_APP_PATH: iosApp
      TESTER_GROUP: "new-release-updates"
      # Note: Setting these specific env vars for an explicit Gradle call is now unnecessary
      # CONFIGURATION: Release
      # SDK_NAME: iphoneos
      # ARCHS: arm64

    steps:
      # ---------- 1. Checkout ----------
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      # ---------- 2. Download Keystore (Retained for Gradle config phase if needed) ----------
      - name: 🔑 Download Keystore Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-signing-keystore
          path: composeApp/

      # ---------- 3. Setup Xcode ----------
      - name: 🛠️ Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      # ---------- 4. Install Firebase Tools ----------
      - name: 🔥 Install Firebase Tools
        run: npm install -g firebase-tools

      # --- REMOVED STEP 5: Building the KMP framework directly with Gradle is the cause of the "Could not infer" error. ---
      # --- Xcode will call Gradle automatically in the next step. ---

      # ---------- 5. Increment iOS build number (renumbered) ----------
      - name: 🔢 Increment iOS Build Number
        run: |
          INFOPLIST="$IOS_APP_PATH/iosApp/Info.plist"
          if [ -f "$INFOPLIST" ]; then
            CURRENT_BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" $INFOPLIST)
            NEW_BUILD_NUMBER=$((CURRENT_BUILD_NUMBER + 1))
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD_NUMBER" $INFOPLIST
            echo "✅ iOS build number incremented: $CURRENT_BUILD_NUMBER → $NEW_BUILD_NUMBER"
          else
            echo "⚠️ Info.plist not found at $INFOPLIST"
          fi

      # ---------- 6. Build and Archive iOS IPA (FIXED STEP) ----------
      - name: 📱 Build and Export iOS IPA
        run: |
          cd $IOS_APP_PATH
          echo "🏗️ Archiving iOS app (The KMP framework build is triggered here)..."
          
          # --- ARCHIVE STEP ---
          # This command tells Xcode to build for a device and produces the archive. 
          # Crucially, Xcode sets the required environment variables (like PLATFORM_NAME) 
          # which the internal Gradle task uses, fixing your original error.
          xcodebuild \
            archive \
            -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/iosApp.xcarchive \
            # Use the NO-SIGNING flag if you don't install a certificate
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          echo "📦 Exporting unsigned IPA..."
          # --- EXPORT STEP ---
          xcodebuild \
            -exportArchive \
            -archivePath build/iosApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      # ---------- 7. Verify IPA (renumbered) ----------
      - name: 🧾 Verify Generated IPA
        run: |
          echo "🔍 Checking for IPA file..."
          IPA_PATH=$(find $IOS_APP_PATH/build -name "*.ipa" -print -quit)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA file found!"
            exit 1
          else
            echo "✅ IPA generated successfully: $IPA_PATH"
            ls -lh "$IPA_PATH"
          fi

      # ---------- 8. Upload iOS to Firebase (renumbered) ----------
      - name: 🚀 Upload iOS Build to Firebase
        run: |
          IPA_PATH=$(find $IOS_APP_PATH/build -name "*.ipa" -print -quit)
          if [ -f "$IPA_PATH" ]; then
            firebase appdistribution:distribute "$IPA_PATH" \
              --app "${{ secrets.IOS_APP_ID }}" \
              --groups "$TESTER_GROUP" \
              --release-notes "🍏 Unsigned iOS build from GitHub Actions (Commit: ${{ github.sha }})" \
              --token "${{ secrets.FIREBASE_TOKEN }}"
          else
            echo "❌ IPA not found, skipping Firebase upload."
          fi