name: 🍏 iOS Build and Distribution (KMP ComposeApp)

on:
  workflow_call:
    secrets:
      IOS_APP_ID: { required: true }
      FIREBASE_TOKEN: { required: true }
      # Android secrets (Removed download step, as they aren't used for iOS)
      KEYSTORE_PASSWORD: { required: true }
      KEY_ALIAS: { required: true }
      KEY_PASSWORD: { required: true }

jobs:
  build_ios:
    runs-on: macos-latest

    env:
      # Top-level iOS project folder
      IOS_APP_PATH: iosApp
      # Nested Xcode project folder relative to the top-level path
      XCODE_PROJECT_PATH: iosApp
      TESTER_GROUP: "new-release-updates"

    steps:
      # 1. Checkout (Unchanged)
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Tools (Unchanged)
      - name: 🛠️ Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      # ----------------------------------------------------
      # ✅ FIX: Install Pods in the correct, nested directory
      # ----------------------------------------------------
      - name: 📦 Install Dependencies (CocoaPods)
        run: |
          # Navigate into the nested Xcode project directory: iosApp/iosApp
          cd $IOS_APP_PATH/$XCODE_PROJECT_PATH 
          
          echo "🔍 Running pod install in $(pwd)"
          pod install --repo-update 
          echo "✅ CocoaPods installed successfully, creating iosApp.xcworkspace."

      # 3. Increment iOS Build Number
      - name: 🔢 Increment iOS Build Number
        run: |
          INFOPLIST="$IOS_APP_PATH/$XCODE_PROJECT_PATH/Info.plist" 
          
          if [ -f "$INFOPLIST" ]; then
            CURRENT_BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" $INFOPLIST)
            NEW_BUILD_NUMBER=$((CURRENT_BUILD_NUMBER + 1))
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD_NUMBER" $INFOPLIST
            echo "✅ iOS build number incremented: $CURRENT_BUILD_NUMBER → $NEW_BUILD_NUMBER"
          else
            echo "❌ Info.plist not found. Job Failed."
            exit 1
          fi

      # 4. Build and Archive iOS IPA
      - name: 📱 Build and Export iOS IPA
        # Must run xcodebuild from the top-level iosApp folder
        run: |
          cd $IOS_APP_PATH 
          echo "🏗️ Archiving iOS app. (Workspace file is now present)..."
          
          # ARCHIVE STEP: Targets the .xcworkspace (now created by the Pods step)
          xcodebuild \
            archive \
            -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/iosApp.xcarchive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          echo "📦 Exporting unsigned IPA..."
          # EXPORT STEP
          xcodebuild \
            -exportArchive \
            -archivePath build/iosApp.xcarchive \
            -exportOptionsPlist $XCODE_PROJECT_PATH/ExportOptions.plist \
            -exportPath build \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      # 5. Verify & 6. Upload iOS to Firebase (Using Firebase CLI)
      - name: 🧾 Verify Generated IPA
        run: |
          IPA_PATH=$(find $IOS_APP_PATH/build -name "*.ipa" -print -quit)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA file found!"
            exit 1
          else
            echo "✅ IPA generated successfully: $IPA_PATH"
          fi

      - name: 🔥 Install Firebase Tools
        run: npm install -g firebase-tools

      - name: 🚀 Upload iOS Build to Firebase
        run: |
          IPA_PATH=$(find $IOS_APP_PATH/build -name "*.ipa" -print -quit)
          if [ -f "$IPA_PATH" ]; then
            firebase appdistribution:distribute "$IPA_PATH" \
              --app "${{ secrets.IOS_APP_ID }}" \
              --groups "$TESTER_GROUP" \
              --release-notes "🍏 CI Build (Commit: ${{ github.sha }})" \
              --token "${{ secrets.FIREBASE_TOKEN }}"
          else
            echo "❌ IPA not found, skipping Firebase upload."
          fi