name: 🍏 iOS Build and Distribution (KMP ComposeApp)

on:
  workflow_call:
    secrets:
      IOS_APP_ID: { required: true }
      FIREBASE_TOKEN: { required: true }
      KEYSTORE_PASSWORD: { required: true }
      KEY_ALIAS: { required: true }
      KEY_PASSWORD: { required: true }

jobs:
  build_ios:
    runs-on: macos-latest

    env:
      IOS_APP_PATH: iosApp
      TESTER_GROUP: "new-release-updates"

    steps:
      # 1. Checkout & 2. Download Artifacts (Unchanged)
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4
      - name: 🔑 Download Keystore Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-signing-keystore
          path: composeApp/

      # 3. Setup Tools (Unchanged)
      - name: 🛠️ Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'
      - name: 🔥 Install Firebase Tools
        run: npm install -g firebase-tools

      # ----------------------------------------------------
      # 💥 NEW FIX STEP: Install Pods to create the .xcworkspace file
      # ----------------------------------------------------
      - name: 📦 Install Dependencies (CocoaPods)
        run: |
          cd $IOS_APP_PATH
          # Use --repo-update to ensure the pod repo is current
          pod install --repo-update 
          echo "✅ CocoaPods installed successfully, creating iosApp.xcworkspace."

      # 4. Increment iOS Build Number (Path logic unchanged, requires Info.plist fix)
      - name: 🔢 Increment iOS Build Number
        run: |
          INFOPLIST="$IOS_APP_PATH/iosApp/Info.plist" 
          
          if [ -f "$INFOPLIST" ]; then
            CURRENT_BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" $INFOPLIST)
            NEW_BUILD_NUMBER=$((CURRENT_BUILD_NUMBER + 1))
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD_NUMBER" $INFOPLIST
            echo "✅ iOS build number incremented: $CURRENT_BUILD_NUMBER → $NEW_BUILD_NUMBER"
          else
            echo "❌ Info.plist not found at $INFOPLIST. Check \$IOS_APP_PATH definition."
            exit 1
          fi

      # 5. Build and Archive iOS IPA (Uses the now-existing .xcworkspace)
      - name: 📱 Build and Export iOS IPA
        run: |
          cd $IOS_APP_PATH
          echo "🏗️ Archiving iOS app..."
          
          # ARCHIVE STEP: Targets the .xcworkspace, which should now exist.
          xcodebuild \
            archive \
            -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/iosApp.xcarchive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          echo "📦 Exporting unsigned IPA..."
          # EXPORT STEP
          xcodebuild \
            -exportArchive \
            -archivePath build/iosApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      # 6. Verify & 7. Upload iOS to Firebase (Unchanged)
      - name: 🧾 Verify Generated IPA
        run: |
          IPA_PATH=$(find $IOS_APP_PATH/build -name "*.ipa" -print -quit)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA file found!"
            exit 1
          else
            echo "✅ IPA generated successfully: $IPA_PATH"
          fi

      - name: 🚀 Upload iOS Build to Firebase
        run: |
          IPA_PATH=$(find $IOS_APP_PATH/build -name "*.ipa" -print -quit)
          if [ -f "$IPA_PATH" ]; then
            firebase appdistribution:distribute "$IPA_PATH" \
              --app "${{ secrets.IOS_APP_ID }}" \
              --groups "$TESTER_GROUP" \
              --release-notes "🍏 CI Build (Commit: ${{ github.sha }})" \
              --token "${{ secrets.FIREBASE_TOKEN }}"
          else
            echo "❌ IPA not found, skipping Firebase upload."
          fi