name: 🍏 iOS Build and Distribution (KMP ComposeApp)

on:
  workflow_call:
    secrets:
      IOS_APP_ID: { required: true }
      FIREBASE_TOKEN: { required: true }
      # Android secrets required for Gradle config phase
      KEYSTORE_PASSWORD: { required: true }
      KEY_ALIAS: { required: true }
      KEY_PASSWORD: { required: true }

jobs:
  build_ios:
    runs-on: macos-latest

    env:
      IOS_APP_PATH: iosApp
      TESTER_GROUP: "new-release-updates"

    steps:
      # ---------- 1. Checkout ----------
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      # ---------- 2. Download Keystore (for Gradle config) ----------
      - name: 🔑 Download Keystore Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-signing-keystore
          path: composeApp/

      # ---------- 3. Setup Xcode ----------
      - name: 🛠️ Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      # ---------- 4. Install Firebase Tools ----------
      - name: 🔥 Install Firebase Tools
        run: npm install -g firebase-tools

      # ---------- 5. Build KMP iOS Framework ----------
      - name: 🧩 Build KMP iOS Framework (Unsigned)
        env:
          XCODE_ARCHS: 'arm64'
          SDK_NAME: 'iphoneos'
        run: |
          echo "🏗️ Building Kotlin Multiplatform (Compose) iOS framework..."
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode \
            -PKEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
            -PKEY_ALIAS=${{ secrets.KEY_ALIAS }} \
            -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }}

      # ---------- 6. Increment iOS build number ----------
      - name: 🔢 Increment iOS Build Number
        run: |
          INFOPLIST="$IOS_APP_PATH/iosApp/Info.plist"
          if [ -f "$INFOPLIST" ]; then
            CURRENT_BUILD_NUMBER=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" $INFOPLIST)
            NEW_BUILD_NUMBER=$((CURRENT_BUILD_NUMBER + 1))
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD_NUMBER" $INFOPLIST
            echo "✅ iOS build number incremented: $CURRENT_BUILD_NUMBER → $NEW_BUILD_NUMBER"
          else
            echo "⚠️ Info.plist not found at $INFOPLIST"
          fi

      # ---------- 7. Build unsigned iOS IPA ----------
      - name: 📱 Build Unsigned iOS IPA
        run: |
          cd $IOS_APP_PATH
          echo "🏗️ Archiving iOS app (unsigned)..."
          xcodebuild \
            -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/iosApp.xcarchive archive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

          echo "📦 Exporting unsigned IPA..."
          xcodebuild \
            -exportArchive \
            -archivePath build/iosApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      # ---------- 8. Verify IPA ----------
      - name: 🧾 Verify Generated IPA
        run: |
          echo "🔍 Checking for IPA file..."
          IPA_PATH=$(find $IOS_APP_PATH/build -name "*.ipa" -print -quit)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA file found!"
            exit 1
          else
            echo "✅ IPA generated successfully: $IPA_PATH"
            ls -lh "$IPA_PATH"
          fi

      # ---------- 9. Upload iOS to Firebase ----------
      - name: 🚀 Upload iOS Build to Firebase
        run: |
          IPA_PATH=$(find $IOS_APP_PATH/build -name "*.ipa" -print -quit)
          if [ -f "$IPA_PATH" ]; then
            firebase appdistribution:distribute "$IPA_PATH" \
              --app "${{ secrets.IOS_APP_ID }}" \
              --groups "$TESTER_GROUP" \
              --release-notes "🍏 Unsigned iOS build from GitHub Actions (Commit: ${{ github.sha }})" \
              --token "${{ secrets.FIREBASE_TOKEN }}"
          else
            echo "❌ IPA not found, skipping Firebase upload."
          fi
